version: '3.8'

services:

  database:
    container_name: myxedb
    image: oracle/database:21.3.0-xe
    env_file:
      - .env.database
    volumes:
      - oradata:/opt/oracle/oradata
  
  development-env:
    container_name: taskapp-dev
    extra_hosts:
      - "host.docker.internal:192.168.5.2"
    image: taskapp-dev:1.0
    build:
      context: .
      dockerfile: ./Dockerfile-dev-env
    environment:
      - NODE_ENV=development
    command: npm run start:debug --prefix /opt/taskapp
    env_file:
      - .env.development
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - taskapp-network
    volumes:
      - .:/opt/taskapp
    restart: unless-stopped
    
networks:
  taskapp-network:

volumes:
  oradata:
  